
_settextposition ( 1,13 ); _outtext( C9);
_settextposition ( 6,0 ); _outtext( C1);
_settextposition ( 6,4 ); _outtext( C2);
_settextposition ( 6,8 ); _outtext( C3);
_settextposition ( 6,49 ); _outtext( C4);
_settextposition ( 6,56 ); _outtext( C5);
_settextposition ( 6,63 ); _outtext( C6);
_settextposition ( 22,65 ); _outtext( C7);



_settextposition ( 0,1 ); _outtext("ษออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป");
_settextposition ( 1,1 ); _outtext("บ");
_settextposition ( 1,26 ); _outtext("DAILY TABLE RENTAL CASH RECIEPTS");
_settextposition ( 1,78 ); _outtext("บ");
_settextposition ( 2,1 ); _outtext("ฬอออัอออัออออออออออออออออออออออออออออออออออออออออัออออออัออออออัอออออออออออออน");
_settextposition ( 3,1 ); _outtext("บ");
_settextposition ( 3,5 ); _outtext("ณ");
_settextposition ( 3,9 ); _outtext("ณ");
_settextposition ( 3,50 ); _outtext("ณ");
_settextposition ( 3,57 ); _outtext("ณ");
_settextposition ( 3,64 ); _outtext("ณ");
_settextposition ( 3,78 ); _outtext("บ");
_settextposition ( 4,1 ); _outtext("บDAYณEMPณEMPLOYEE NAME OR MEMO");
_settextposition ( 4,50 ); _outtext("ณ");
_settextposition ( 4,52 ); _outtext("TIME");
_settextposition ( 4,57 ); _outtext("ณ");
_settextposition ( 4,59 ); _outtext("TIME");
_settextposition ( 4,64 ); _outtext("ณ");
_settextposition ( 4,66 ); _outtext("RECIEPTS");
_settextposition ( 4,78 ); _outtext("บ");
_settextposition ( 5,1 ); _outtext("วฤฤฤลฤฤฤลฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤลฤฤฤฤฤฤลฤฤฤฤฤฤลฤฤฤฤฤฤฤฤฤฤฤฤฤถ");
_settextposition ( 6,1 ); _outtext("บ");
_settextposition ( 6,5 ); _outtext("ณ");
_settextposition ( 6,9 ); _outtext("ณ");
_settextposition ( 6,50 ); _outtext("ณ");
_settextposition ( 6,57 ); _outtext("ณ");
_settextposition ( 6,64 ); _outtext("ณ");
_settextposition ( 6,78 ); _outtext("บ");
_settextposition ( 7,1 ); _outtext("บ");
_settextposition ( 7,5 ); _outtext("ณ");
_settextposition ( 7,9 ); _outtext("ณ");
_settextposition ( 7,50 ); _outtext("ณ");
_settextposition ( 7,57 ); _outtext("ณ");
_settextposition ( 7,64 ); _outtext("ณ");
_settextposition ( 7,78 ); _outtext("บ");
_settextposition ( 8,1 ); _outtext("บ");
_settextposition ( 8,5 ); _outtext("ณ");
_settextposition ( 8,9 ); _outtext("ณ");
_settextposition ( 8,50 ); _outtext("ณ");
_settextposition ( 8,57 ); _outtext("ณ");
_settextposition ( 8,64 ); _outtext("ณ");
_settextposition ( 8,78 ); _outtext("บ");
_settextposition ( 9,1 ); _outtext("บ");
_settextposition ( 9,5 ); _outtext("ณ");
_settextposition ( 9,9 ); _outtext("ณ");
_settextposition ( 9,50 ); _outtext("ณ");
_settextposition ( 9,57 ); _outtext("ณ");
_settextposition ( 9,64 ); _outtext("ณ");
_settextposition ( 9,78 ); _outtext("บ");
_settextposition ( 10,1 ); _outtext("บ");
_settextposition ( 10,5 ); _outtext("ณ");
_settextposition ( 10,9 ); _outtext("ณ");
_settextposition ( 10,50 ); _outtext("ณ");
_settextposition ( 10,57 ); _outtext("ณ");
_settextposition ( 10,64 ); _outtext("ณ");
_settextposition ( 10,78 ); _outtext("บ");
_settextposition ( 11,1 ); _outtext("บ");
_settextposition ( 11,5 ); _outtext("ณ");
_settextposition ( 11,9 ); _outtext("ณ");
_settextposition ( 11,50 ); _outtext("ณ");
_settextposition ( 11,57 ); _outtext("ณ");
_settextposition ( 11,64 ); _outtext("ณ");
_settextposition ( 11,78 ); _outtext("บ");
_settextposition ( 12,1 ); _outtext("บ");
_settextposition ( 12,5 ); _outtext("ณ");
_settextposition ( 12,9 ); _outtext("ณ");
_settextposition ( 12,50 ); _outtext("ณ");
_settextposition ( 12,57 ); _outtext("ณ");
_settextposition ( 12,64 ); _outtext("ณ");
_settextposition ( 12,78 ); _outtext("บ");
_settextposition ( 13,1 ); _outtext("บ");
_settextposition ( 13,5 ); _outtext("ณ");
_settextposition ( 13,9 ); _outtext("ณ");
_settextposition ( 13,50 ); _outtext("ณ");
_settextposition ( 13,57 ); _outtext("ณ");
_settextposition ( 13,64 ); _outtext("ณ");
_settextposition ( 13,78 ); _outtext("บ");
_settextposition ( 14,1 ); _outtext("บ");
_settextposition ( 14,5 ); _outtext("ณ");
_settextposition ( 14,9 ); _outtext("ณ");
_settextposition ( 14,50 ); _outtext("ณ");
_settextposition ( 14,57 ); _outtext("ณ");
_settextposition ( 14,64 ); _outtext("ณ");
_settextposition ( 14,78 ); _outtext("บ");
_settextposition ( 15,1 ); _outtext("บ");
_settextposition ( 15,5 ); _outtext("ณ");
_settextposition ( 15,9 ); _outtext("ณ");
_settextposition ( 15,50 ); _outtext("ณ");
_settextposition ( 15,57 ); _outtext("ณ");
_settextposition ( 15,64 ); _outtext("ณ");
_settextposition ( 15,78 ); _outtext("บ");
_settextposition ( 16,1 ); _outtext("บ");
_settextposition ( 16,5 ); _outtext("ณ");
_settextposition ( 16,9 ); _outtext("ณ");
_settextposition ( 16,50 ); _outtext("ณ");
_settextposition ( 16,57 ); _outtext("ณ");
_settextposition ( 16,64 ); _outtext("ณ");
_settextposition ( 16,78 ); _outtext("บ");
_settextposition ( 17,1 ); _outtext("บ");
_settextposition ( 17,5 ); _outtext("ณ");
_settextposition ( 17,9 ); _outtext("ณ");
_settextposition ( 17,50 ); _outtext("ณ");
_settextposition ( 17,57 ); _outtext("ณ");
_settextposition ( 17,64 ); _outtext("ณ");
_settextposition ( 17,78 ); _outtext("บ");
_settextposition ( 18,1 ); _outtext("บ");
_settextposition ( 18,5 ); _outtext("ณ");
_settextposition ( 18,9 ); _outtext("ณ");
_settextposition ( 18,50 ); _outtext("ณ");
_settextposition ( 18,57 ); _outtext("ณ");
_settextposition ( 18,64 ); _outtext("ณ");
_settextposition ( 18,78 ); _outtext("บ");
_settextposition ( 19,1 ); _outtext("บ");
_settextposition ( 19,5 ); _outtext("ณ");
_settextposition ( 19,9 ); _outtext("ณ");
_settextposition ( 19,50 ); _outtext("ณ");
_settextposition ( 19,57 ); _outtext("ณ");
_settextposition ( 19,64 ); _outtext("ณ");
_settextposition ( 19,78 ); _outtext("บ");
_settextposition ( 20,1 ); _outtext("บ");
_settextposition ( 20,5 ); _outtext("ณ");
_settextposition ( 20,9 ); _outtext("ณ");
_settextposition ( 20,50 ); _outtext("ณ");
_settextposition ( 20,57 ); _outtext("ณ");
_settextposition ( 20,64 ); _outtext("ณ");
_settextposition ( 20,78 ); _outtext("บ");
_settextposition ( 21,1 ); _outtext("ฬอออฯอออฯออออออออออออออออออออออออออออออออออออออออฯออออออฯออออออฯอออออออออออออน");
_settextposition ( 22,1 ); _outtext("บ");
_settextposition ( 22,57 ); _outtext("TOTAL -");
_settextposition ( 22,78 ); _outtext("บ");
_settextposition ( 23,1 ); _outtext("ศออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ");

